version: "3.3"

services:

  builder:
    user: builder
    build: ./docker/builder
    volumes:
      - ./:/tmp/spotifm

  icecast2:
    image: pltnk/icecast2
    hostname: icecast2
    volumes:
      - type: bind
        source: ./etc/icecast.xml
        target: /etc/icecast2/icecast.xml
    networks:
      fm:
        aliases:
          - icecast2
    ports:
      - "0.0.0.0:8000:8000"
    restart: always

  streamer:
    user: user
    build: ./docker/streamer
    volumes:
      - type: bind
        source: ./target/release/spotifm
        target: /usr/local/bin/spotifm
      - type: bind
        source: ./etc/pulse.liq
        target: /etc/liquidsoap/pulse.liq
      - type: bind
        source: ./config.json
        target: /etc/spotifm.json
    networks:
      fm:
        aliases:
          - streamer
    ports:
      - "0.0.0.0:9090:9090"
    depends_on:
      - icecast2
    restart: always

  ircbot:
    user: node
    build: ./docker/ircbot
    volumes:
      - type: bind
        source: ./ircbot.json
        target: /etc/ircbot.json
    networks:
      fm:
        aliases:
          - ircbot
    depends_on:
      - streamer
    restart: always

  discordbot:
    user: node
    build: ./docker/discordbot
    volumes:
      - type: bind
        source: ./discordbot.json
        target: /etc/discordbot.json
    networks:
      fm:
        aliases:
          - discordbot
    depends_on:
      - streamer
    restart: always

networks:
  fm:
