version: "3.3"
services:
  build-spotify-fm:
    build: build-spotify-fm
    volumes:
      - ../src:/tmp/spotify-fm/src
      - ../target:/tmp/spotify-fm/target
      - type: bind
        source: ../Cargo.toml
        target: /tmp/spotify-fm/Cargo.toml
  streamer:
    build: streamer
    volumes:
      - type: bind
        source: ../target/release/spotify-fm
        target: /usr/local/bin/spotify-fm
    ports:
      - "0.0.0.0:8088:8000"
      - "0.0.0.0:9090:9090"
    depends_on:
      - build-spotify-fm
    env_file:
      - config.env
      - dev.env
    restart: always
